import "server-only";
import type { RowDataPacket } from "mysql2";
import { db,withTransaction } from "@/lib/db";
import { writeAdminAudit } from "@/lib/admin-audit";

const permissionKeys=["can_list","can_read","can_create","can_comment","can_upload","can_download","can_moderate"] as const;
interface BoardRow extends RowDataPacket{id:number;board_key:string;name:string;description:string|null;status:string;visibility:string;allow_comments:number;max_attachments:number;max_attachment_bytes:number;sort_order:number;post_count:number}
interface PermissionRow extends RowDataPacket{board_id:number;role_key:string;can_list:number;can_read:number;can_create:number;can_comment:number;can_upload:number;can_download:number;can_moderate:number}
export type BoardPermissionKey=typeof permissionKeys[number];
export interface AdminBoard {id:number;key:string;name:string;description:string;status:string;visibility:string;allowComments:boolean;maxAttachments:number;maxAttachmentBytes:number;sortOrder:number;postCount:number;permissions:Record<string,Set<BoardPermissionKey>>}

export async function listAdminBoards(locale:string){const [rows]=await db.query<BoardRow[]>(`SELECT b.id,b.board_key,COALESCE(bt.name,ko.name,b.board_key) name,COALESCE(bt.description,ko.description,'') description,b.status,b.visibility,b.allow_comments,b.max_attachments,b.max_attachment_bytes,b.sort_order,COUNT(p.id) post_count FROM boards b LEFT JOIN board_translations bt ON bt.board_id=b.id AND bt.locale_code=? LEFT JOIN board_translations ko ON ko.board_id=b.id AND ko.locale_code='ko' LEFT JOIN posts p ON p.board_id=b.id AND p.status<>'deleted' GROUP BY b.id,bt.name,bt.description,ko.name,ko.description ORDER BY b.sort_order,b.id`,[locale]);const [perms]=await db.query<PermissionRow[]>(`SELECT brp.*,r.role_key FROM board_role_permissions brp JOIN roles r ON r.id=brp.role_id ORDER BY r.id`);return rows.map<AdminBoard>(r=>{const permissions:Record<string,Set<BoardPermissionKey>>={};for(const p of perms.filter(x=>x.board_id===r.id)){permissions[p.role_key]=new Set(permissionKeys.filter(k=>Boolean(p[k])))}return{id:r.id,key:r.board_key,name:r.name,description:r.description??"",status:r.status,visibility:r.visibility,allowComments:Boolean(r.allow_comments),maxAttachments:Number(r.max_attachments),maxAttachmentBytes:Number(r.max_attachment_bytes),sortOrder:Number(r.sort_order),postCount:Number(r.post_count),permissions}})}

export async function saveBoard(input:{actorId:number;originalKey?:string;key:string;locale:string;name:string;description:string;status:string;visibility:string;allowComments:boolean;maxAttachments:number;maxAttachmentMb:number;sortOrder:number;permissions:Record<string,Set<BoardPermissionKey>>}){await withTransaction(async c=>{let boardId:number;if(input.originalKey){const [rows]=await c.query<(RowDataPacket&{id:number})[]>("SELECT id FROM boards WHERE board_key=? FOR UPDATE",[input.originalKey]);if(!rows[0])throw new Error("게시판을 찾을 수 없습니다.");boardId=rows[0].id;await c.execute("UPDATE boards SET board_key=?,status=?,visibility=?,allow_comments=?,max_attachments=?,max_attachment_bytes=?,sort_order=? WHERE id=?",[input.key,input.status,input.visibility,input.allowComments,input.maxAttachments,input.maxAttachmentMb*1024*1024,input.sortOrder,boardId])}else{const [result]=await c.execute<import("mysql2").ResultSetHeader>("INSERT INTO boards (board_key,default_locale_code,status,visibility,allow_comments,max_attachments,max_attachment_bytes,sort_order) VALUES (?,? ,?,?,?,?,?,?)",[input.key,input.locale,input.status,input.visibility,input.allowComments,input.maxAttachments,input.maxAttachmentMb*1024*1024,input.sortOrder]);boardId=result.insertId}
    await c.execute("INSERT INTO board_translations (board_id,locale_code,name,description) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description)",[boardId,input.locale,input.name,input.description||null]);
    for(const [roleKey,grants] of Object.entries(input.permissions)){await c.execute(`INSERT INTO board_role_permissions (board_id,role_id,can_list,can_read,can_create,can_comment,can_upload,can_download,can_moderate) SELECT ?,id,?,?,?,?,?,?,? FROM roles WHERE role_key=? ON DUPLICATE KEY UPDATE can_list=VALUES(can_list),can_read=VALUES(can_read),can_create=VALUES(can_create),can_comment=VALUES(can_comment),can_upload=VALUES(can_upload),can_download=VALUES(can_download),can_moderate=VALUES(can_moderate)`,[boardId,...permissionKeys.map(k=>grants.has(k)),roleKey])}
  });await writeAdminAudit(input.actorId,"board",input.key,input.originalKey?"updated":"created",{locale:input.locale})}
export {permissionKeys};
