import "server-only";
import type { ResultSetHeader,RowDataPacket } from "mysql2";
import { db,withTransaction } from "@/lib/db";
import { createPublicId } from "@/lib/ids";
import { writeAdminAudit } from "@/lib/admin-audit";

const slugByKey:Record<string,string>={guyak:"old-testament",sinyak:"new-testament",yuksa:"history",jojik:"systematic",silchun:"practical",sungyo:"missions"};
const keyBySlug=Object.fromEntries(Object.entries(slugByKey).map(([k,v])=>[v,k]));
interface CategoryRow extends RowDataPacket{id:number;category_key:string;name:string;sort_order:number;is_active:number;course_count:number}
interface CourseRow extends RowDataPacket{id:number;public_id:string;course_code:string;category_key:string;category_name:string;name:string;youtube_playlist_id:string|null;sort_order:number;is_active:number;lesson_count:number;visible_count:number}
interface LessonRow extends RowDataPacket{public_id:string;lesson_number:number;youtube_video_id:string|null;title:string|null;sort_order:number;is_visible:number;is_available:number}
export interface LectureCategory{id:number;key:string;slug:string;name:string;sortOrder:number;isActive:boolean;courseCount:number}
export interface LectureCourse{id:number;publicId:string;code:string;categoryKey:string;categorySlug:string;categoryName:string;name:string;playlistId:string|null;sortOrder:number;isActive:boolean;lessonCount:number;visibleCount:number}
export interface LectureLesson{publicId:string;number:number;videoId:string|null;title:string|null;sortOrder:number;isVisible:boolean;isAvailable:boolean}

const categorySelect=`SELECT c.id,c.category_key,COALESCE(t.name,en.name,ko.name,c.category_key) name,c.sort_order,c.is_active,COUNT(lc.id) course_count FROM lecture_categories c LEFT JOIN lecture_category_translations t ON t.category_id=c.id AND t.locale_code=? LEFT JOIN lecture_category_translations en ON en.category_id=c.id AND en.locale_code='en' LEFT JOIN lecture_category_translations ko ON ko.category_id=c.id AND ko.locale_code='ko' LEFT JOIN lecture_courses lc ON lc.category_id=c.id`;
function mapCategory(r:CategoryRow):LectureCategory{return{id:r.id,key:r.category_key,slug:slugByKey[r.category_key]??r.category_key,name:r.name,sortOrder:Number(r.sort_order),isActive:Boolean(r.is_active),courseCount:Number(r.course_count)}}
function mapCourse(r:CourseRow):LectureCourse{return{id:r.id,publicId:r.public_id,code:r.course_code,categoryKey:r.category_key,categorySlug:slugByKey[r.category_key]??r.category_key,categoryName:r.category_name,name:r.name,playlistId:r.youtube_playlist_id,sortOrder:Number(r.sort_order),isActive:Boolean(r.is_active),lessonCount:Number(r.lesson_count),visibleCount:Number(r.visible_count)}}
export async function getLectureCategories(locale:string,admin=false){const [rows]=await db.query<CategoryRow[]>(`${categorySelect} ${admin?"":"WHERE c.is_active=TRUE"} GROUP BY c.id,t.name,en.name,ko.name ORDER BY c.sort_order,c.id`,[locale]);return rows.map(mapCategory)}
export async function getLectureCourses(locale:string,categorySlug:string,admin=false){const key=keyBySlug[categorySlug]??categorySlug;const [rows]=await db.query<CourseRow[]>(`SELECT lc.id,lc.public_id,lc.course_code,c.category_key,COALESCE(ct.name,cen.name,cko.name,c.category_key) category_name,COALESCE(t.name,en.name,ko.name,lc.course_code) name,lc.youtube_playlist_id,lc.sort_order,lc.is_active,COUNT(ll.id) lesson_count,SUM(ll.is_visible) visible_count FROM lecture_courses lc JOIN lecture_categories c ON c.id=lc.category_id LEFT JOIN lecture_category_translations ct ON ct.category_id=c.id AND ct.locale_code=? LEFT JOIN lecture_category_translations cen ON cen.category_id=c.id AND cen.locale_code='en' LEFT JOIN lecture_category_translations cko ON cko.category_id=c.id AND cko.locale_code='ko' LEFT JOIN lecture_course_translations t ON t.course_id=lc.id AND t.locale_code=? LEFT JOIN lecture_course_translations en ON en.course_id=lc.id AND en.locale_code='en' LEFT JOIN lecture_course_translations ko ON ko.course_id=lc.id AND ko.locale_code='ko' LEFT JOIN lecture_lessons ll ON ll.course_id=lc.id WHERE c.category_key=? ${admin?"":"AND c.is_active=TRUE AND lc.is_active=TRUE"} GROUP BY lc.id,ct.name,cen.name,cko.name,t.name,en.name,ko.name ORDER BY lc.sort_order,lc.id`,[locale,locale,key]);return rows.map(mapCourse)}
export async function getLectureCourse(locale:string,courseCode:string,admin=false){const [rows]=await db.query<CourseRow[]>(`SELECT lc.id,lc.public_id,lc.course_code,c.category_key,COALESCE(ct.name,cen.name,cko.name,c.category_key) category_name,COALESCE(t.name,en.name,ko.name,lc.course_code) name,lc.youtube_playlist_id,lc.sort_order,lc.is_active,COUNT(ll.id) lesson_count,SUM(ll.is_visible) visible_count FROM lecture_courses lc JOIN lecture_categories c ON c.id=lc.category_id LEFT JOIN lecture_category_translations ct ON ct.category_id=c.id AND ct.locale_code=? LEFT JOIN lecture_category_translations cen ON cen.category_id=c.id AND cen.locale_code='en' LEFT JOIN lecture_category_translations cko ON cko.category_id=c.id AND cko.locale_code='ko' LEFT JOIN lecture_course_translations t ON t.course_id=lc.id AND t.locale_code=? LEFT JOIN lecture_course_translations en ON en.course_id=lc.id AND en.locale_code='en' LEFT JOIN lecture_course_translations ko ON ko.course_id=lc.id AND ko.locale_code='ko' LEFT JOIN lecture_lessons ll ON ll.course_id=lc.id WHERE lc.course_code=? ${admin?"":"AND c.is_active=TRUE AND lc.is_active=TRUE"} GROUP BY lc.id,ct.name,cen.name,cko.name,t.name,en.name,ko.name LIMIT 1`,[locale,locale,courseCode]);if(!rows[0])return null;const course=mapCourse(rows[0]);const [lessons]=await db.query<LessonRow[]>(`SELECT public_id,lesson_number,youtube_video_id,title,sort_order,is_visible,is_available FROM lecture_lessons WHERE course_id=? ${admin?"":"AND is_visible=TRUE"} ORDER BY sort_order,lesson_number`,[course.id]);return{...course,lessons:lessons.map(r=>({publicId:r.public_id,number:Number(r.lesson_number),videoId:r.youtube_video_id,title:r.title,sortOrder:Number(r.sort_order),isVisible:Boolean(r.is_visible),isAvailable:Boolean(r.is_available)}))}}
export async function getAdminLectureCatalog(locale:string){const categories=await getLectureCategories(locale,true);const groups=await Promise.all(categories.map(async category=>({category,courses:await getLectureCourses(locale,category.slug,true)})));return groups}

export async function saveLectureCategory(input:{actorId:number;key:string;locale:string;name:string;sortOrder:number;isActive:boolean}){await withTransaction(async c=>{await c.execute("UPDATE lecture_categories SET sort_order=?,is_active=? WHERE category_key=?",[input.sortOrder,input.isActive,input.key]);await c.execute("INSERT INTO lecture_category_translations (category_id,locale_code,name) SELECT id,?,? FROM lecture_categories WHERE category_key=? ON DUPLICATE KEY UPDATE name=VALUES(name)",[input.locale,input.name,input.key])});await writeAdminAudit(input.actorId,"lecture_category",input.key,"updated",{locale:input.locale})}
export async function saveLectureCourse(input:{actorId:number;originalCode?:string;code:string;categoryKey:string;locale:string;name:string;playlistId:string|null;sortOrder:number;isActive:boolean}){await withTransaction(async c=>{const [cats]=await c.query<(RowDataPacket&{id:number})[]>("SELECT id FROM lecture_categories WHERE category_key=?",[input.categoryKey]);if(!cats[0])throw new Error("분류를 찾을 수 없습니다.");let id:number;if(input.originalCode){const [rows]=await c.query<(RowDataPacket&{id:number})[]>("SELECT id FROM lecture_courses WHERE course_code=? FOR UPDATE",[input.originalCode]);if(!rows[0])throw new Error("과목을 찾을 수 없습니다.");id=rows[0].id;await c.execute("UPDATE lecture_courses SET course_code=?,category_id=?,youtube_playlist_id=?,sort_order=?,is_active=? WHERE id=?",[input.code,cats[0].id,input.playlistId,input.sortOrder,input.isActive,id])}else{const [r]=await c.execute<ResultSetHeader>("INSERT INTO lecture_courses (public_id,course_code,category_id,youtube_playlist_id,sort_order,is_active) VALUES (?,?,?,?,?,?)",[createPublicId(),input.code,cats[0].id,input.playlistId,input.sortOrder,input.isActive]);id=r.insertId}await c.execute("INSERT INTO lecture_course_translations (course_id,locale_code,name) VALUES (?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name)",[id,input.locale,input.name])});await writeAdminAudit(input.actorId,"lecture_course",input.code,input.originalCode?"updated":"created",{locale:input.locale})}
export async function saveLectureLesson(input:{actorId:number;courseCode:string;publicId:string;number:number;title:string|null;videoId:string|null;sortOrder:number;isVisible:boolean;isAvailable:boolean}){await db.execute("UPDATE lecture_lessons ll JOIN lecture_courses lc ON lc.id=ll.course_id SET ll.lesson_number=?,ll.title=?,ll.youtube_video_id=?,ll.sort_order=?,ll.is_visible=?,ll.is_available=? WHERE ll.public_id=? AND lc.course_code=?",[input.number,input.title,input.videoId,input.sortOrder,input.isVisible,input.isAvailable,input.publicId,input.courseCode]);await writeAdminAudit(input.actorId,"lecture_lesson",input.publicId,"updated",{courseCode:input.courseCode,number:input.number})}
export async function addLectureLesson(input:{actorId:number;courseCode:string}){const [courses]=await db.query<(RowDataPacket&{id:number;next_number:number})[]>("SELECT lc.id,COALESCE(MAX(ll.lesson_number),0)+1 next_number FROM lecture_courses lc LEFT JOIN lecture_lessons ll ON ll.course_id=lc.id WHERE lc.course_code=? GROUP BY lc.id",[input.courseCode]);if(!courses[0])throw new Error("과목을 찾을 수 없습니다.");await db.execute("INSERT INTO lecture_lessons (public_id,course_id,lesson_number,sort_order) VALUES (?,?,?,?)",[createPublicId(),courses[0].id,courses[0].next_number,courses[0].next_number]);await writeAdminAudit(input.actorId,"lecture_course",input.courseCode,"lesson_added")}
