"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { canManageUsers,getCurrentUser } from "@/lib/auth";
import { addLectureLesson,saveLectureCategory,saveLectureCourse,saveLectureLesson } from "@/lib/lectures";
async function actor(locale:string){const u=await getCurrentUser();if(!u||!canManageUsers(u))redirect(`/${locale}/admin`);return u}
const categorySchema=z.object({key:z.string().regex(/^[a-z0-9_-]+$/),name:z.string().trim().min(1).max(150),sortOrder:z.coerce.number().int().min(0).max(9999)});
export async function saveCategoryAction(locale:string,formData:FormData){const u=await actor(locale),p=categorySchema.safeParse(Object.fromEntries(formData));if(!p.success)redirect(`/${locale}/admin/lectures?error=${encodeURIComponent("분류 입력값을 확인해 주세요.")}`);await saveLectureCategory({...p.data,actorId:u.id,locale,isActive:formData.get("isActive")==="on"});revalidatePath(`/${locale}/lectures`);redirect(`/${locale}/admin/lectures?status=${encodeURIComponent("분류를 저장했습니다.")}`)}
const courseSchema=z.object({originalCode:z.string().optional(),code:z.string().trim().regex(/^[A-Za-z0-9_-]{2,40}$/).transform(v=>v.toUpperCase()),categoryKey:z.string().regex(/^[a-z0-9_-]+$/),name:z.string().trim().min(1).max(200),playlistId:z.string().trim().max(100),sortOrder:z.coerce.number().int().min(0).max(9999)});
export async function saveCourseAction(locale:string,formData:FormData){const u=await actor(locale),p=courseSchema.safeParse(Object.fromEntries(formData));if(!p.success)redirect(`/${locale}/admin/lectures?error=${encodeURIComponent("과목 입력값을 확인해 주세요.")}`);try{await saveLectureCourse({...p.data,actorId:u.id,locale,playlistId:p.data.playlistId||null,isActive:formData.get("isActive")==="on"})}catch(e){redirect(`/${locale}/admin/lectures?error=${encodeURIComponent(e instanceof Error?e.message:"저장하지 못했습니다.")}`)}revalidatePath(`/${locale}/lectures`);redirect(`/${locale}/admin/lectures?status=${encodeURIComponent("과목을 저장했습니다.")}`)}
const lessonSchema=z.object({publicId:z.string().length(26),number:z.coerce.number().int().min(1).max(999),title:z.string().trim().max(250),videoId:z.string().trim().max(20),sortOrder:z.coerce.number().int().min(0).max(9999)});
export async function saveLessonAction(locale:string,courseCode:string,formData:FormData){const u=await actor(locale),p=lessonSchema.safeParse(Object.fromEntries(formData));if(!p.success)redirect(`/${locale}/admin/lectures/${courseCode}?error=${encodeURIComponent("차시 입력값을 확인해 주세요.")}`);await saveLectureLesson({...p.data,actorId:u.id,courseCode,title:p.data.title||null,videoId:p.data.videoId||null,isVisible:formData.get("isVisible")==="on",isAvailable:formData.get("isAvailable")==="on"});revalidatePath(`/${locale}/lectures/${courseCode}`);redirect(`/${locale}/admin/lectures/${courseCode}?status=${encodeURIComponent(`${p.data.number}강을 저장했습니다.`)}`)}
export async function addLessonAction(locale:string,courseCode:string){const u=await actor(locale);await addLectureLesson({actorId:u.id,courseCode});revalidatePath(`/${locale}/admin/lectures/${courseCode}`);redirect(`/${locale}/admin/lectures/${courseCode}?status=${encodeURIComponent("새 차시를 추가했습니다.")}`)}
